version: "3.9"
services:
  postgresserver:
    image: postgres:13.3
    container_name: postgresserver
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testuserpass"
      PGDATA: /var/lib/postgresql/data/some_name/
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
       - pgdata:/var/lib/postgresql/data
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  webapp:
    image: vladimir0691/webapp:latest
    environment:
      - "POSTGRES_CONNECTION_STRING=User ID=testuser;Password=testuserpass;Host=postgresserver;Port=5432;Database=testdb;Pooling=true;"
      - "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true"
      - "ASPNETCORE_URLS=http://+:80"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "APP_UID=1654"
      - "ASPNETCORE_HTTP_PORTS=8080"
      - "DOTNET_RUNNING_IN_CONTAINER=true"
      - "DOTNET_VERSION=8.0.4"
      - "ASPNET_VERSION=8.0.4"
    ports:
      - "443:443"
      - "80:80"
    working_dir: /app
    links:
       - postgresserver
    depends_on:
       - "postgresserver"
    networks:
       - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
     driver: bridge