<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>41aa5927-ee01-4024-8de7-019aa6e1e8ed</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebApp.BLL\WebApp.BLL.Contracts\WebApp.BLL.Contracts.csproj" />
    <ProjectReference Include="..\WebApp.BLL\WebApp.BLL.Services\WebApp.BLL.Services.csproj" />
    <ProjectReference Include="..\WebApp.DAL\WebApp.DAL.Entities\WebApp.DAL.Entities.csproj" />
    <ProjectReference Include="..\WebApp.DAL\WebApp.DAL.NpgsqlRepositories\WebApp.DAL.NpgsqlRepositories.csproj" />
  </ItemGroup>

</Project>
